apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: example-realm-user
  labels:
    app: sso
spec:
  user:
    username: "realm_user"
    firstName: "Realm"
    lastName: "User"
    email: "realm_user@redhat.com"
    enabled: True
    emailVerified: False
  realmSelector:
    matchLabels:
      app: sso
